management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/flowable?nullCatalogMeansCurrent=true

flowable:
  idm:
    enabled: false
  http:
    connect-timeout: 5s
    socket-timeout: 5s
    request-retry-limit: 0
    disable-cert-verify: false
  eventregistry:
    enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    org.flowable.engine.impl.persistence.entity.*: debug
    org.flowable.task.service.impl.persistence.entity.*: debug

debug: true